name: tercer workflow

on: 
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Java application
    runs-on: windows-2019
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build native with Maven
      run: mvn -B package
    - name: Upload jar for next job
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target
        retention-days: 1
    - name: ejecutar test unitario
      run: mvn -B '-Dtest = es.urjc.code.daw.library.unitary.*Test' test
    - name: ejecutar api rest test
      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
    - name: ejecutar selenium test
      run : mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test

  