name: primer workflow

on: 
  push:
    branches:
      [release/0.1]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build native with Maven
      run: mvn -B package -DskipTests
    - name: ejecutar test unitario
      run: mvn -B '-Dtest = es.urjc.code.daw.library.unitary.*Test' test
    - name: ejecutar api rest test
      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test