name: primer workflow

on: 
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build native with Maven
      run: mvn -B package
    - name: ejecutar test unitario
      run: src\test\java\es\urjc\code\daw\library\unitary\BookServiceUnitaryTest.java
    - name: ejecutar api rest test
      run: C:\Users\pilah\ais-p.lahoz-m.garciaco-2021\src\test\java\es\urjc\code\daw\library\e2e\rest\RestTest.java